version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: rosafilgueira/kakfa_docker
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 129.114.108.142
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


