version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper_local
  kafka:
    image: rosafilgueira/kakfa_docker
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 129.114.108.142
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    links:
      - zookeeper
    container_name: kafka_local
  elk:
    build: .
    image: elk_kafka:latest
    depends_on:
        - kafka
        - zookeeper
    ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"
        - "5000:5000"
    container_name: elk_local
